name: qlocktwo
description: QlockTwo powered by Flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  dropdown_button2:
  flutter:
    sdk: flutter
  google_fonts:
  intl:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_launcher_icons:

flutter:
  uses-material-design: true
  assets:
    - "assets/settings/settings.json"
    - "assets/settings/de.json"
    - "assets/settings/en.json"
    - "assets/icons/"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/qclocktwo_de.jpg"
  min_sdk_android: 30 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/qclocktwo_de.jpg"
    # background_color: "#hexcode"
    # theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/qclocktwo_de.jpg"
    icon_size: 48 # min:48, max:256, default: 48
